grpc:
  server:
    port: 20100
    security:
      enabled: on
      certificateChain: ${MICA_SERVER_CERTIFICATE}
      privateKey: ${MICA_SERVER_KEY}
      client-auth: optional
      trustCertCollection: ${MICA_SERVER_ROOT_CA}

mica:
  host: ${MICA_HOST}
  port: 443
  rootCAPEM: ${MICA_CLIENT_ROOT_CA}
  clientKeyPEM: ${MICA_CLIENT_KEY}
  clientCertificatePEM: ${MICA_CLIENT_CERTIFICATE}

